import type { Metadata } from 'next'

import './globals.css'
import '@repo/ui/styles.css'
import { inter } from '@repo/ui/components'

export const metadata: Metadata = {
	title: 'Create Turborepo',
	description: 'Generated by create turbo',
}

export default function RootLayout({ children }: { children: React.ReactNode }): JSX.Element {
	return (
		<html lang="en">
			<body className={inter.className}>{children}</body>
		</html>
	)
}
