name: Continuous Deployment - Deploy on Push

on:
  push:
    branches:
      - main
    paths-ignore:
      - 'README.md'

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Check Out Repo
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Cache Docker layers
        uses: actions/cache@v4
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-docker-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-docker-

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and Push Docker Images
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ./apps/user-app/Dockerfile
          push: true
          tags: vardaankhattar/user-app:latest

      - name: Build and Push Docker Images
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ./apps/scheduler/Dockerfile
          push: true
          tags: vardaankhattar/scheduler:latest

      - name: Build and Push Docker Images
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ./apps/merchant-app/Dockerfile
          push: true
          tags: vardaankhattar/merchant-app:latest

      - name: Build and Push Docker Images
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ./apps/bank_webhook/Dockerfile
          push: true
          tags: vardaankhattar/bank_webhook:latest

      - name: Verify Pushed Images
        run: |
          docker pull vardaankhattar/user-app:latest
          docker pull vardaankhattar/scheduler:latest
          docker pull vardaankhattar/merchant-app:latest
          docker pull vardaankhattar/bank_webhook:latest

      - name: Deploy to EC2
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_KEY }}
          script: |
            # Pull the latest images
            sudo docker pull vardaankhattar/user-app:latest
            sudo docker pull vardaankhattar/scheduler:latest
            sudo docker pull vardaankhattar/merchant-app:latest
            sudo docker pull vardaankhattar/bank_webhook:latest

            sudo docker stop user-app || true
            sudo docker stop scheduler || true
            sudo docker stop merchant-app || true
            sudo docker stop bank_webhook || true

            sudo docker rm user-app || true
            sudo docker rm scheduler || true
            sudo docker rm merchant-app || true
            sudo docker rm bank_webhook || true

            # Run database migrations if needed
            # Uncomment and customize the following if you have migrations to run
            # sudo docker run --rm \
            #   -e DATABASE_URL=${{ secrets.DATABASE_URL }} \
            #   vardaankhattar/user-app:latest \
            #   npx prisma migrate deploy

            # Run the applications with environment variables
            sudo docker run --restart unless-stopped -d \
              --name user-app \
              -p ${{ secrets.USER_APP_PORT }}:${{ secrets.USER_APP_PORT }} \
              -e PORT=${{ secrets.USER_APP_PORT }} \
              -e DATABASE_URL=${{ secrets.DATABASE_URL }} \
              -e MERCHANT_APP_ROUTE=${{ secrets.MERCHANT_APP_ROUTE }} \
              -e NEXT_PUBLIC_CLERK_PUBLISHABLE_KEY=${{ secrets.USER_NEXT_PUBLIC_CLERK_PUBLISHABLE_KEY }} \
              -e CLERK_SECRET_KEY=${{ secrets.USER_CLERK_SECRET_KEY }} \
              -e WEBHOOK_SECRET=${{ secrets.USER_WEBHOOK_SECRET }} \
              -e BANK_WEBHOOK_API=${{ secrets.BANK_WEBHOOK_API }} \
              -e NEXT_PUBLIC_CLERK_SIGN_IN_URL=${{ secrets.NEXT_PUBLIC_CLERK_SIGN_IN_URL }} \
              -e NEXT_PUBLIC_CLERK_SIGN_UP_URL=${{ secrets.NEXT_PUBLIC_CLERK_SIGN_UP_URL }} \
              -e NEXT_PUBLIC_CLERK_SIGN_IN_FORCE_REDIRECT_URL=${{ secrets.NEXT_PUBLIC_CLERK_SIGN_IN_FORCE_REDIRECT_URL }} \
              -e NEXT_PUBLIC_CLERK_SIGN_UP_FORCE_REDIRECT_URL=${{ secrets.NEXT_PUBLIC_CLERK_SIGN_UP_FORCE_REDIRECT_URL }} \
              vardaankhattar/user-app:latest

            sudo docker run --restart unless-stopped -d \
              --name merchant-app \
              -p ${{ secrets.MERCHANT_APP_PORT }}:${{ secrets.MERCHANT_APP_PORT }} \
              -e PORT=${{ secrets.MERCHANT_APP_PORT }} \
              -e DATABASE_URL=${{ secrets.DATABASE_URL }} \
              -e NEXT_PUBLIC_CLERK_PUBLISHABLE_KEY=${{ secrets.MERCHANT_NEXT_PUBLIC_CLERK_PUBLISHABLE_KEY }} \
              -e CLERK_SECRET_KEY=${{ secrets.MERCHANT_CLERK_SECRET_KEY }} \
              -e WEBHOOK_SECRET=${{ secrets.MERCHANT_WEBHOOK_SECRET }} \
              -e BANK_WEBHOOK_API=${{ secrets.BANK_WEBHOOK_API }} \
              -e NEXT_PUBLIC_CLERK_SIGN_IN_URL=${{ secrets.NEXT_PUBLIC_CLERK_SIGN_IN_URL }} \
              -e NEXT_PUBLIC_CLERK_SIGN_UP_URL=${{ secrets.NEXT_PUBLIC_CLERK_SIGN_UP_URL }} \
              -e NEXT_PUBLIC_CLERK_SIGN_IN_FORCE_REDIRECT_URL=${{ secrets.NEXT_PUBLIC_CLERK_SIGN_IN_FORCE_REDIRECT_URL }} \
              -e NEXT_PUBLIC_CLERK_SIGN_UP_FORCE_REDIRECT_URL=${{ secrets.NEXT_PUBLIC_CLERK_SIGN_UP_FORCE_REDIRECT_URL }} \
              vardaankhattar/merchant-app:latest

            sudo docker run --restart unless-stopped -d \
              --name scheduler \
              -e API_HOST=${{ secrets.SCHEDULER_API_HOST }} \
              -e DATABASE_URL=${{ secrets.DATABASE_URL }} \
              vardaankhattar/scheduler:latest

            sudo docker run --restart unless-stopped -d \
              --name bank_webhook \
              -p ${{ secrets.BANK_WEBHOOK_PORT }}:${{ secrets.BANK_WEBHOOK_PORT }} \
              -e PORT=${{ secrets.BANK_WEBHOOK_PORT }} \
              -e DATABASE_URL=${{ secrets.DATABASE_URL }} \
              vardaankhattar/bank_webhook:latest
